version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
workflows:
  test_my_app:
    jobs:
      - test
